### ISSUE TITLE
overwriteWithEmptyValue is forced to `true` when merging an object involving maps

### ISSUE THREAD

**Issue by liggitt** [darccio/mergo#187]
https://github.com/imdario/mergo/pull/85 introduced a bug that can leave `overwriteWithEmptyValue` set to true if a map is encountered, but one of the `continue` or `return` statements is called before calling `deepMerge` (which reset to `false`)

https://github.com/imdario/mergo/blob/29fb3d3bdc5512887f1dc9aedde6a0fed407fa8f/map.go#L72-L100

https://github.com/imdario/mergo/pull/133 made the bug worse by removing the reset to `false` in `deepMerge`, so now, any merge involving a map leaves `overwriteWithEmptyValue` set to true for all remaining merges.

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/darccio) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/darccio/mergo/issues/187">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/darccio/mergo/issues/187/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/darccio/mergo/issues/187/pledge.svg">
</picture>
</a>

**Comment by imdario** [comment]
@liggitt I regret I'm unable to fix this in a quick way. Can you provide a PR?

**Comment by darccio** [comment]
Fixing this in v2.

**Comment by haircommander** [comment]
hey @darccio I am curious about v2 timeline.  I believe we're hitting this issue in https://github.com/kubernetes/kubernetes/pull/121193 and it's not clear to me how to work around this behavior.

**Comment by darccio** [comment]
@haircommander There is no planned timeline. I work on Mergo in my spare time. I will appreciate any help on this.
