### ISSUE TITLE
Details on which fields/attributes were updated

### ISSUE THREAD

**Issue by jankrynauw** [darccio/mergo#195]
Hi, is there perhaps a way to see which fields have been updated after a merge?

**Comment by ruanspies** [comment]
Is this something that is of relevance to this project @imdario? If so, I am happy to contribute to this.

To expand on my understanding of what @jankrynauw is seeking using the demo:

```
src := Foo{
	A: "one",
	B: 2,
}
dest := Foo{
	A: "two",
}
mergo.Merge(&dest, src)
fmt.Println(dest)
// Will print
// {two 2}
```

It would be useful to have a way to know that field `A` comes from `dest` and field `B` from `src`.

My suggestion would be to have a `map[string]string` with the keys being the struct's field paths and the value being the name of the relevant struct. In this example:

```
map[string]int32{
	"A":       "dest",
	"B":      "src",
}
```

**Comment by imdario** [comment]
@ruanspies Not sure about this change.
