### ISSUE TITLE
Merge without override assume false is a valid non empty type

### ISSUE THREAD

**Issue by kotyara85** [darccio/mergo#201]
Here's an example

```
type Option struct {
	test    bool
}

o := Option{}

mergo.Merge(&o, &Option{test: true})

```

In this example test will be false. WithOverride won't really work here, because any other type will be overwritten in this case.
I guess custom transformers will help here?

**Comment by nilsgstrabo** [comment]
According to docs [](https://pkg.go.dev/github.com/imdario/mergo#Merge) this is expected behavior
`Mergo won't merge unexported (private) fields`
Rename field **test** to **Test** and it will work as expected
