### ISSUE TITLE
WithSliceDeepCopy cannot merge nums in slice. Suggestion: Recomplete it as WithRecursiveOverride

### ISSUE THREAD

**Issue by aceaura** [darccio/mergo#225]
with golang 1.19
```go
package main

import (
	"encoding/json"
	"fmt"

	"github.com/imdario/mergo"
)

func main() {
	s1 := `{"a":[{"b":1},2,3]}`
	s2 := `{"a":[{"b":4},5]}`
	var m1, m2 map[string]interface{}
	json.Unmarshal([]byte(s1), &m1)
	json.Unmarshal([]byte(s2), &m2)
	mergo.Merge(&m1, m2, mergo.WithSliceDeepCopy)
        fmt.Println(m1)
}
```
expected: map[a:[map[b:4] 5 3]]
reality: map[a:[map[b:4] 2 3]]

Suggestion： SliceDeepCopy is just a fake option with too many bugs. Please remove it and  readd  `WithRecursiveOverride`. 
exmaple:
```go
func main() {
	s1 := `{"a":[{"b":1, "c": 2},[3,4],5,6]}`
	s2 := `{"a":[{"b":7},[8], 9]}`
	var m1, m2 map[string]interface{}
	json.Unmarshal([]byte(s1), &m1)
	json.Unmarshal([]byte(s2), &m2)
	mergo.Merge(&m1, m2, mergo.WithRecursiveOverride)
	fmt.Println(m1)
}
```
expected: 
map[a:[map[b:7 c:2] [8 4] 9 6]]

**Comment by darccio** [comment]
@aceaura This would be merging with overwrite by index. It won't be implemented, at least in v1.

Feel free to provide a PR.

**Comment by aengelberg** [comment]
> This would be merging with overwrite by index

May I ask what is the difference between "slice deep copy" and "overwrite by index"? It seems like the latter is necessary for the former to work at all, and I'm wondering what I'm doing wrong trying to get slices to merge deeply.
