### ISSUE TITLE
New module path breaks go install of package with indirect dependency on mergo

### ISSUE THREAD

**Issue by jmikolay22** [darccio/mergo#240]
I have an indirect dependency on this package via github.com/elwinar/rambler. When running:

`
go install github.com/elwinar/rambler@latest
`

I get the follow error now, due to the new module path for mergo

```
github.com/imdario/mergo: github.com/imdario/mergo@v1.0.0: parsing go.mod:
        module declares its path as: dario.cat/mergo
                but was required as: github.com/imdario/mergo
```

**Comment by kiwansky** [comment]
We have the same issue on multiple projects.

**Comment by fa-gb** [comment]
the root question: why?

![image](https://github.com/imdario/mergo/assets/129736719/d5fc1d2b-bce8-49fe-996d-0ebf1984eab7)

**Comment by imdario** [comment]
@jmikolay22 @kiwansky @fa-gb You need to modify your imports to match the new module URL `dario.cat/mergo`.

This change was announced a few weeks ago: https://github.com/imdario/mergo/discussions/236

**Comment by imdario** [comment]
@jmikolay22 In the particular case of `rambler`, it is quite curious, as cloning and installing just works:

![imagen](https://github.com/imdario/mergo/assets/163009/edd929a7-0e6e-4392-bfb7-260fbc429683)

It seems that installing a tool with `go install $url@latest` resolves to 1.0.0 instead of 0.3.11. `go build` seems to resolve it as expected to 0.3.11:

![imagen](https://github.com/imdario/mergo/assets/163009/1132d283-9de8-4fd0-8a69-1c1bec9b8223)

**Comment by imdario** [comment]
@kiwansky I saw you opened the issue https://github.com/crossplane/crossplane-runtime/issues/469. What other projects have you found affected by this change? Thanks!

**Comment by kiwansky** [comment]
Only our closed source project inside the company currently.
From our side we needed to update webdevops/go-replace to 22.10.0 looks like the same behavior as with rambler. So for us it's working again.

**Comment by ramonskie** [comment]
this is also happening in https://github.com/vmware-archive/texplate

**Comment by imdario** [comment]
@ramonskie Running `texplate`'s `scripts/build` seem to work. How are you installing?

**Comment by ramonskie** [comment]
i'm running it as `go install github.com/pivotal-cf/texplate@latest`

**Comment by imdario** [comment]
@ramonskie `go install` seem to resolve versions in an unexpected way, while `go build` looks happy to use the exact version. Chek my previous comment: https://github.com/imdario/mergo/issues/240#issuecomment-1605726804

**Comment by ramonskie** [comment]
yeah its a strange issue. thanks for looking it up though

**Comment by andig** [comment]
Is there a related Go issue?

**Comment by darccio** [comment]
Closing it with a suggestion from another issue:

Iinstead of replacing the imports, to use the `replace` statement in your go.mod while Sprig updates to use the new URL too.

```
module github.com/evcc-io/evcc

go 1.21

replace github.com/imdario/mergo => dario.cat/mergo v1.0.0
```

After this, remove from `go.mod` all the other references to mergo, and run:

```
go get -u
go mod tidy
```

It's possible that it will return a different warning, but it makes sense:

> go: finding module for package dario.cat/mergo
> go: found dario.cat/mergo in dario.cat/mergo v1.0.0
> go: dario.cat/mergo@v1.0.0 used for two different module paths (dario.cat/mergo and github.com/imdario/mergo)
