### ISSUE TITLE
module declares its path as: dario.cat/mergo but was required as: github.com/imdario/mergo

### ISSUE THREAD

**Issue by fred1268** [darccio/mergo#248]
When using mergo, we got the following `go mod` error:
```
go: github.com/imdario/mergo@v1.0.0: parsing go.mod:
        module declares its path as: dario.cat/mergo
                but was required as: github.com/imdario/mergo
        restoring github.com/imdario/mergo@v0.3.16
```

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/darccio) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/darccio/mergo/issues/248">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/darccio/mergo/issues/248/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/darccio/mergo/issues/248/pledge.svg">
</picture>
</a>

**Comment by gregorypa** [comment]
we have same issue.

**Comment by sentriz** [comment]
bit of a hack, but i'm using `go mod edit -replace github.com/imdario/mergo=dario.cat/mergo@v1.0.0` as a workaround

**Comment by brennanjl** [comment]
Just do `go get -u dario.cat/mergo` instead.  It uses a vanity url, hence the error.

**Comment by sentriz** [comment]
its still an issue for me after @brennanjl and then doing a go mod tidy

**Comment by pplmx** [comment]
> Just do `go get -u dario.cat/mergo` instead. It uses a vanity url, hence the error.

After running the above command, and then run `go get -u ./...`, the issue re-occurred.
In my project, mergo is an indirect

**Comment by vaughany** [comment]
FWIW, in my `go.mod` I had to use 
```
require (
	github.com/imdario/mergo v1.0.0 // indirect
        ...
)
```
..and then this `replace` statement at the top:
```
replace github.com/imdario/mergo => dario.cat/mergo v1.0.0
```

**Comment by rockdaboot** [comment]
The replace trick doesn't work. A `go mod tidy` afterwards or `go get -u all` results in
```
go: dario.cat/mergo@v1.0.0 used for two different module paths (dario.cat/mergo and github.com/imdario/mergo)
```

Both modules are indirect dependencies. So I can only wait until all direct dependencies updated to dario.cat =)
