### ISSUE TITLE
dario.cat has expired

### ISSUE THREAD

**Issue by jacmet** [darccio/mergo#252]
daria.cat no longer resolves here. According to the whois info it expired yesterday:

```
Registry Expiry Date: 2024-06-01T07:05:04.361Z
```

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/darccio) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/darccio/mergo/issues/252">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/darccio/mergo/issues/252/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/darccio/mergo/issues/252/pledge.svg">
</picture>
</a>

**Comment by John-Appleseed** [comment]
Gitea docker build commands errors out 8 minutes into the build process. 
```
/go/pkg/mod/github.com/go-git/go-git/v5@v5.11.0/repository.go:17:2: unrecognized import path "dario.cat/mergo": https fet
ch: Get "https://dario.cat/mergo?go-get=1": dial tcp: lookup dario.cat on 172.16.12.1:53: server misbehaving
```

**Comment by techknowlogick** [comment]
Thanks for this report. I will close it now as the domain has been renewed, and so using a replace in go.mod is no longer needed.

**Comment by avishayt** [comment]
Failing to fetch as well with the same error message

**Comment by darccio** [comment]
Sorry, it was solved as soon as I detected it.
