### ISSUE TITLE
Upgrade dependencies go get -u ./... causing errors

### ISSUE THREAD

**Issue by williamohara** [darccio/mergo#258]
getting this error when I upgrade my dependencies - it's not blocking but is there something I am supposed to do to prevent the error?

[Error - 1:33:45 PM] Request workspace/executeCommand failed.
  Message: err: exit status 1: stderr: go: -d flag is deprecated. -d=true is a no-op
go: github.com/imdario/mergo@upgrade (v1.0.1) requires github.com/imdario/mergo@v1.0.1: parsing go.mod:
	module declares its path as: dario.cat/mergo
	        but was required as: github.com/imdario/mergo

**Comment by procinger** [comment]
When I tried to update the package today, I got the same error. Is the release just broken?

**Comment by darccio** [comment]
@williamohara Use the new vanity URL `dario.cat/mergo` for any `v1.x` version. This change happened more than one year ago (see #240).

**Comment by williamohara** [comment]
For me its a dependency in the Azure SDK for go - I'll just reach out to the azure team and tell them to do it :)
